// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ainuuqUSzfN3g0gTjl3OHtKcvfUnTl4',
    appId: '1:386356240136:web:e81d3e4d156961ebeb96bd',
    messagingSenderId: '386356240136',
    projectId: 'spidey-94f3e',
    authDomain: 'spidey-94f3e.firebaseapp.com',
    storageBucket: 'spidey-94f3e.firebasestorage.app',
    measurementId: 'G-Y5TREYKF32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcE2E-HgqSsNhgsjB70yhcscdoJ4lstKc',
    appId: '1:386356240136:android:040c7a3969113226eb96bd',
    messagingSenderId: '386356240136',
    projectId: 'spidey-94f3e',
    storageBucket: 'spidey-94f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaygGUD_UuB40PkBmi7jMgiAWAc4EJq1A',
    appId: '1:386356240136:ios:76660c22c5c164c8eb96bd',
    messagingSenderId: '386356240136',
    projectId: 'spidey-94f3e',
    storageBucket: 'spidey-94f3e.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.pesaTools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaygGUD_UuB40PkBmi7jMgiAWAc4EJq1A',
    appId: '1:386356240136:ios:76660c22c5c164c8eb96bd',
    messagingSenderId: '386356240136',
    projectId: 'spidey-94f3e',
    storageBucket: 'spidey-94f3e.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.pesaTools',
  );
}
